"""Work out every generated file and its contents, write them, or compare them with what is on disk."""

from __future__ import annotations

import json
from pathlib import Path

from . import arm, kql
from .rules import AREAS, CONTENT_ROOT, RULES_DIR, Rule, check_rules, duration_seconds, load_rules
from .workbooks import WORKBOOKS_DIR, Workbook, check_workbooks, gallery_text, load_workbooks, workbook_queries

ALL_RULES = "all-rules.json"
ALL_WORKBOOKS = "all-workbooks.json"
CATALOGUE = "CATALOGUE.md"
GENERATED_NOTE = "<!-- Generated by Content_Build (python -m sentinel_content build). Edit the .kql files, not this file. -->"


def load_all() -> tuple[list[Rule], list[Workbook], dict[str, dict[str, str]]]:
    return load_rules(), load_workbooks(), kql.load_schema()


def problems(rules: list[Rule], books: list[Workbook], schema: dict[str, dict[str, str]]) -> list[str]:
    """Everything wrong with the sources. Nothing is generated while this list is not empty."""
    found = check_rules(rules, schema) + check_workbooks(books, rules, schema)
    if not rules:
        found.append("no rule files found under Detection-rules/")
    if not books:
        found.append("no workbook sources found under Workbooks/src/")
    return found


def readable_duration(text: str) -> str:
    """PT1H -> '1 hour', P14D -> '14 days'."""
    seconds = duration_seconds(text)
    for size, unit in ((86400, "day"), (3600, "hour"), (60, "minute")):
        if seconds % size == 0:
            count = seconds // size
            return f"{count} {unit}{'' if count == 1 else 's'}"
    return text


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def catalogue(rules: list[Rule], books: list[Workbook]) -> str:
    """The rule catalogue as Markdown: one summary table, then every rule in full."""
    book_by_area = {book.area: book for book in books}
    lines = [
        "# Detection rule catalogue",
        "",
        GENERATED_NOTE,
        "",
        f"{len(rules)} scheduled analytics rules in {len(AREAS)} areas. Each rule's alerts are shown on the",
        "Detections tab of the workbook for its area.",
        "",
        "| Id | Rule | Severity | Tactics | Tables | Runs every | Reads |",
        "|---|---|---|---|---|---|---|",
    ]
    for rule in rules:
        lines.append(
            f"| [{rule.id}](#{rule.id.lower()}) | {_cell(rule.title)} | {rule.severity} | "
            f"{', '.join(rule.tactics) or 'Operational'} | {', '.join(f'`{t}`' for t in rule.tables)} | "
            f"{readable_duration(rule.frequency)} | {readable_duration(rule.period)} |"
        )
    for area, details in AREAS.items():
        area_rules = [rule for rule in rules if rule.area == area]
        if not area_rules:
            continue
        book = book_by_area.get(area)
        lines += ["", f"## {details['title']}", ""]
        if book is not None:
            lines.append(f"Workbook: [{book.name}](../Workbooks/{book.file}.json). Template: [deploy/{area}.json](deploy/{area}.json).")
        for rule in area_rules:
            techniques = ", ".join((*rule.techniques, *rule.sub_techniques)) or "none"
            entities = "; ".join(
                f"{kind} ({', '.join(column for _, column in pairs)})" for kind, pairs in rule.entities
            ) or "none"
            lines += [
                "",
                f"### {rule.id}",
                "",
                f"**{rule.title}**  ",
                f"Source: [{rule.path.name}]({area}/{rule.path.name})",
                "",
                "| | |",
                "|---|---|",
                f"| Severity | {rule.severity} |",
                f"| MITRE ATT&CK | {', '.join(rule.tactics) or 'Operational rule, no tactic'}; techniques: {techniques} |",
                f"| Tables | {', '.join(f'`{t}`' for t in rule.tables)} |",
                f"| Schedule | every {readable_duration(rule.frequency)}, reading the last {readable_duration(rule.period)} |",
                f"| Entities | {_cell(entities)} |",
                "",
                f"**What it finds.** {rule.description}",
                "",
                f"**False positives.** {rule.false_positives}",
                "",
                f"**Tuning.** {rule.tuning}",
                "",
                f"**Response.** {rule.response}",
            ]
            if rule.references:
                lines += ["", "**References.** " + " ".join(f"<{link}>" for link in rule.references)]
    return "\n".join(lines) + "\n"


def generated_files(rules: list[Rule], books: list[Workbook], enabled: bool = False) -> dict[Path, str]:
    """Every generated file, as {path relative to Microsoft_Sentinel: contents}."""
    files: dict[Path, str] = {}
    rules_dir = RULES_DIR.relative_to(CONTENT_ROOT)
    books_dir = WORKBOOKS_DIR.relative_to(CONTENT_ROOT)
    files[rules_dir / "deploy" / ALL_RULES] = arm.template_text(arm.rules_template(rules, enabled))
    for area in AREAS:
        area_rules = [rule for rule in rules if rule.area == area]
        if area_rules:
            files[rules_dir / "deploy" / f"{area}.json"] = arm.template_text(arm.rules_template(area_rules, enabled))
    files[rules_dir / CATALOGUE] = catalogue(rules, books)
    for book in books:
        files[books_dir / f"{book.file}.json"] = gallery_text(book, rules)
    files[books_dir / "deploy" / ALL_WORKBOOKS] = arm.template_text(arm.workbooks_template(books, rules))
    return files


def write_files(files: dict[Path, str], root: Path) -> list[Path]:
    """Write the files under root and return the ones whose contents changed."""
    changed = []
    for relative, text in files.items():
        target = root / relative
        if target.exists() and target.read_text(encoding="utf-8") == text:
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text, encoding="utf-8", newline="\n")
        changed.append(relative)
    return changed


def stale_files(files: dict[Path, str], root: Path) -> list[str]:
    """Generated files that are missing or differ from what the sources produce now."""
    stale = []
    for relative, text in files.items():
        target = root / relative
        if not target.exists():
            stale.append(f"{relative.as_posix()} is missing")
        elif target.read_text(encoding="utf-8") != text:
            stale.append(f"{relative.as_posix()} is out of date")
    deploy = root / RULES_DIR.relative_to(CONTENT_ROOT) / "deploy"
    expected = {relative.name for relative in files if relative.parent.name == "deploy"}
    if deploy.is_dir():
        for path in sorted(deploy.glob("*.json")):
            if path.name not in expected:
                stale.append(f"{path.relative_to(root).as_posix()} has no rules behind it; delete it")
    return stale


def query_export(rules: list[Rule], books: list[Workbook]) -> str:
    """Every query with the columns its result must contain, for the semantic check in kql-check."""
    queries = []
    for rule in rules:
        queries.append(
            {
                "id": rule.id,
                "source": f"Detection-rules/{rule.area}/{rule.path.name}",
                "query": kql.strip_comments(rule.query),
                "columns": rule.output_columns,
                "exact": [],
            }
        )
    for book in books:
        for tab_and_title, query in workbook_queries(book, rules):
            item = _item_for(book, rules, tab_and_title)
            settings = item.settings
            columns = [settings.get(key) for key in ("label", "value", "note", "severity", "link")]
            exact = [*settings.get("bars", ()), *settings.get("heat", ()), *settings.get("hide", ())]
            queries.append(
                {
                    "id": f"{book.file}: {tab_and_title}",
                    "source": f"Workbooks/src/{book.path.name}",
                    "query": kql.fill_placeholders(kql.strip_comments(query)),
                    "columns": [column for column in (*columns, *exact) if column],
                    # Workbook formatters match a column by name; a second column that contains the
                    # name could pick up the same formatting, so these must not be substrings.
                    "exact": [column for column in (*columns, *exact) if column],
                }
            )
    return json.dumps(queries, indent=1, ensure_ascii=False) + "\n"


def _item_for(book: Workbook, rules: list[Rule], label: str):
    from .workbooks import all_tabs

    for tab in all_tabs(book, rules):
        for index, item in enumerate(tab.items, start=1):
            if item.kind != "text" and f"{tab.name} / {index}. {item.settings.get('title', item.kind)}" == label:
                return item
    raise KeyError(label)
